{{- if and .Values.global.ingress.traefik.enabled .Values.global.appflowyWeb.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-cors
spec:
  headers:
    accessControlAllowMethods:
      - "GET"
      - "OPTIONS"
      - "PUT"
    accessControlAllowHeaders:
      - "*"
    accessControlAllowOriginList:
      - {{ .Values.global.appflowyWeb.url }}
    accessControlMaxAge: {{ .Values.global.appflowyWeb.corsMaxAge }}
    addVaryHeader: true
{{- end }}
