# Default values for appflowy-gotrue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  fqdn: "http://appflowy.mydomain.com"
  scheme: "http"
  domain: "appflowy.mydomain.com"
  secret:
    name: appflowy
    postgres:
      gotrue:
        postgresPassword:
          key: gotruePostgresPassword
          value: password
        databaseUrl:
          key: gotrueDatabaseUrl
    oauth:
      googleClientSecret:
        key: oauthGoogleClientSecret
        value: ""
      discordClientSecret:
        key: oauthDiscordClientSecret
        value: ""
      githubClientSecret:
        key: oauthGithubClientSecret
        value: ""
      appleClientSecret:
        key: oauthAppleClientSecret
        value: ""
    jwt:
      key: jwtSecret
      value: hello456
    smtp:
      password:
        key: smtpPassword
        value: password

replicaCount: 1

image:
  repository: appflowyinc/gotrue
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80

jwt:
  expiry: 3600

mailer:
  enabled: false
  adminEmail: "admin@example.com"
  autoconfirm: false

oauth:
  google:
    enabled: false
    clientId: ""
  discord:
    enabled: false
    clientId: ""
  github:
    enabled: false
    clientId: ""
  apple:
    enabled: false
    clientId: ""

ingress:
  enabled: true
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  className: nginx

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

readinessProbe:
  httpGet:
    path: /health
    port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}

extraEnv: []
