{{- if .Values.global.ingress.nginx.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-api
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: {{ .Values.global.ingress.cors.allowOrigin | quote }}
    nginx.ingress.kubernetes.io/cors-allow-headers: "Content-Type, Authorization, Accept, Client-Version"
    nginx.ingress.kubernetes.io/cors-max-age: {{ .Values.global.ingress.cors.maxAge | quote }}
spec:
  ingressClassName: {{ .Values.global.ingress.nginx.className }}
  rules:
    - host: {{ .Values.global.external_host }}
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "appflowy-cloud.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
