# Default values for appflowy-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: appflowyinc/appflowy_cloud
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80

logLevel: "info"
redis:
  uri: "redis://appflowy-redis-headless:6379"
gotrue:
  baseUrl: "http://appflowy-gotrue"
  adminEmail: "admin@example.com"
s3:
  createBucket: "true"
  bucket: "appflowy"
  useMinio: "true"
  minioUrl: "http://appflowy-minio:9000"
  accessKey: ""
accessControl:
  enabled: true

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

readinessProbe:
  httpGet:
    path: /metrics
    port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
