# Default values for appflowy-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1

image:
  repository: appflowyinc/appflowy_cloud
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

service:
  type: ClusterIP
  port: 80

# -- Stdout log level
logLevel: "info"
redis:
  # -- Redis URI
  uri: "redis://appflowy-redis-headless:6379"
gotrue:
  # -- GoTrue base URL
  baseUrl: "http://appflowy-gotrue"
  # -- GoTrue admin user, will be created by AppFlowy Cloud if not exists.
  adminEmail: "admin@example.com"
s3:
  # -- Create bucket on startup. If false, bucket must be created manually.
  createBucket: "true"
  # -- S3 Bucket name
  bucket: "appflowy"
  # -- Set this to true when using Minio or other S3-compatible services.
  useMinio: "true"
  # -- Url for the S3-compatible service
  minioUrl: "http://appflowy-minio:9000"
  # -- S3 access key
  accessKey: ""
accessControl:
  # -- Enable access control
  enabled: true

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

readinessProbe:
  httpGet:
    path: /metrics
    port: http

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
