
{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appflowy-cloud.fullname" . }}-ws
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: {{ .Values.ingress.ws.proxyReadTimeout | quote }}
    {{- .Values.ingress.ws.annotations | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /ws
            pathType: Prefix
            backend:
              service:
                name: {{ include "appflowy-cloud.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}