{{- if .Values.global.ingress.traefik.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "appflowy-gotrue.strip-prefix-middleware.fullname" . }}
spec:
  stripPrefix:
    prefixes:
      - /gotrue
{{- end }}
