{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "appflowy-gotrue.fullname" . }}
  annotations: {{ .Values.ingress.annotations | toYaml | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          - path: /gotrue(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "appflowy-gotrue.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}