apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.global.secret.name }}
  labels:
    {{- include "appflowy.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.global.secret.data }}
  {{- range $key, $value := . }}
  {{ if $value }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
  {{- end }}
  {{- end }}
  appflowyDatabaseUrl: {{ include "appflowy.appflowyDatabase.url" . | b64enc }}
  gotrueDatabaseUrl: {{ include "appflowy.gotrueDatabase.url" . | b64enc }}
